site_name: Kolena
site_description: Python client for Kolena's machine learning (ML) testing and debugging platform
site_url: https://docs.kolena.io
strict: false  # TODO: flip to true

theme:
  name: material
  logo: assets/images/wordmark-white.svg
  favicon: assets/images/favicon.png
  custom_dir: docs/overrides
  font:
    text: Inter
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default  # TODO: custom kolena-light theme
      toggle:
        icon: material/toggle-switch
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate  # TODO: custom kolena-dark theme
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Switch to light mode"
  features:
    # - content.tabs.link
    # - navigation.tabs
    # - navigation.path  # breadcrumbs
    - navigation.footer
    - content.action.edit
    - announce.dismiss
    # - navigation.instant  # SPA-style navigation, doesn't play nicely with banner
    - navigation.tabs
    - navigation.sections
    - toc.follow
    # - navigation.top
    - content.code.copy

repo_name: kolenaIO/kolena
repo_url: https://github.com/kolenaIO/kolena
edit_uri: edit/trunk/docs/

markdown_extensions:
  - admonition  # callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


watch:
  - kolena

extra_css:
  - css/theme.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            merge_init_into_class: true
            members_order: source  # sort members in the order they are defined
            show_docstring_attributes: true
            # docstring_section_style: spacy  # TODO: switch on? better for long types
            # separate_signature, line_length, and show_signature_annotations should all be on or off
            # separate_signature: true
            # line_length: 80
            # show_signature_annotations: true
  - social  # render social media cards for copy+paste
  - search:
      lang: en

copyright: Copyright &copy; 2021-2023 Kolena
extra:
  homepage: https://kolena.io
  generator: false  # TODO: this removes the theme info from footer -- we should sponsor project
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kolenaIO/kolena
      name: Kolena on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kolena-ai
      name: Kolena on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kolenaIO
      name: Kolena on Twitter

nav:
  - Home: index.md
  - Getting Started:
    - Installation: setup/installation.md
    - Initialization: setup/initialization.md
  - Using Kolena: []
  - Advanced Usage: []
  - API Reference:
    - <code>kolena.initialize</code>: reference/initialize.md
    - <code>kolena.errors</code>: reference/errors.md
    - <code>kolena.workflow</code>:
      # - Module Index: reference/workflow/index.md
      - "Data Objects (Test Sample, Ground Truth, Inference)":
        - <code>test_sample</code>: reference/workflow/test_sample.md
        - <code>ground_truth</code>: reference/workflow/ground_truth.md
        - <code>inference</code>: reference/workflow/inference.md
        - Annotations: reference/workflow/annotation.md
        - Assets: reference/workflow/asset.md
      - <code>define_workflow</code>: reference/workflow/define_workflow.md
      - <code>TestCase</code>: reference/workflow/test_case.md
      - <code>TestSuite</code>: reference/workflow/test_suite.md
      - <code>Model</code>: reference/workflow/model.md
      - <code>Evaluator</code>: reference/workflow/evaluator.md
      - <code>test</code>: reference/workflow/test_run.md
      # TODO: remove extras?
      - Extras: reference/workflow/extras.md
    - Legacy:
      - Built-in Workflows:
        - <code>kolena.classification</code>: reference/built-in/classification.md
        - <code>kolena.detection</code>: reference/built-in/detection.md
        - <code>kolena.fr</code>:
          - <code>Model</code>: reference/built-in/fr/model.md
          - <code>TestImages</code>: reference/built-in/fr/test_images.md
          - <code>TestCase</code>: reference/built-in/fr/test_case.md
          - <code>TestSuite</code>: reference/built-in/fr/test_suite.md
          - <code>TestRun</code>: reference/built-in/fr/test_run.md
          - <code>datatypes</code>: reference/built-in/fr/datatypes.md
  - Metrics Guide: []
  - Help: []
