site_name: Kolena
site_description: Python client for Kolena's machine learning (ML) testing and debugging platform
site_url: https://docs.kolena.io
strict: true


theme:
  name: material
  custom_dir: docs/theme
  font:
    text: Inter
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default  # TODO: custom kolena-light theme
      toggle:
        icon: material/toggle-switch
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate  # TODO: custom kolena-dark theme
      toggle:
        icon: material/toggle-switch-off-outline
        name: "Switch to light mode"
  features:
    # - content.tabs.link
    # - navigation.tabs
    # - navigation.path  # breadcrumbs
    - navigation.footer
    - content.action.edit
    - announce.dismiss
  logo: wordmark-white.svg
  favicon: favicon.png

repo_name: kolenaIO/kolena
repo_url: https://github.com/kolenaIO/kolena
edit_uri: edit/trunk/docs/

markdown_extensions:
  - admonition  # callouts

watch:
  - kolena

extra_css:
  - css/theme.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
            # show_signature_annotations: true
  - social  # render social media cards for copy+paste

copyright: Copyright &copy; 2021-2023 Kolena
extra:
  generator: false  # TODO: this removes the theme info from footer -- we should sponsor project
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kolenaIO/kolena
      name: Kolena on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kolena-ai
      name: Kolena on LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kolenaIO
      name: Kolena on Twitter


nav:
  - Getting Started:
    - Installation: setup/installation.md
    - Initialization: setup/initialization.md
